# Generated by Django 3.2.21 on 2023-09-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ingenium', '0002_auto_20230918_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='high',
            name='image',
            field=models.CharField(default='ingenium.jpeg', max_length=64),
        ),
    ]
